/*
 * generated by Xtext 2.10.0
 */
package com.uk.eightpillars.nmtran


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class NmTranRuntimeModule extends AbstractNmTranRuntimeModule {
}
