/*
 * generated by Xtext 2.10.0
 */
package com.uk.eightpillars.nmtran


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class NmTranStandaloneSetup extends NmTranStandaloneSetupGenerated {

	def static void doSetup() {
		new NmTranStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
