/*
 * generated by Xtext 2.13.0
 */
package com.uk.eightpillars.nmtran.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class NmTranUiModule extends AbstractNmTranUiModule {
}
